'use client';

import { createWeb3Modal, EIP6963Connector } from '@web3modal/wagmi/react';
import { configureChains, createConfig, WagmiConfig } from 'wagmi';
import { ReactNode } from 'react';
import { WalletConnectConnector } from '@wagmi/connectors/walletConnect';
import { InjectedConnector } from '@wagmi/connectors/injected';
import { walletConnectProvider } from '@web3modal/wagmi';
import config from '@/config';
import { publicProvider } from 'wagmi/providers/public';

const projectId = process.env.NEXT_PUBLIC_WALLET_CONNECT_ID!;

const metadata = {
	name: 'Web3 kick-starter template',
	description: 'Generated by Ramin',
	url: 'https://giveth.io',
	icons: ['https://giveth.io/images/currencies/giv/24.svg'],
};

const chains = config.CHAINS;
const { publicClient } = configureChains(chains, [
	walletConnectProvider({ projectId }),
	publicProvider(),
]);
const wagmiConfig = createConfig({
	autoConnect: false,
	connectors: [
		new WalletConnectConnector({
			chains,
			options: { projectId, showQrModal: false, metadata },
		}),
		new EIP6963Connector({ chains }),
		new InjectedConnector({ chains, options: { shimDisconnect: true } }),
	],
	publicClient,
});

createWeb3Modal({
	wagmiConfig,
	projectId,
	chains,
	themeMode: 'light',
});

export function Web3Modal({ children }: { children: ReactNode }) {
	return <WagmiConfig config={wagmiConfig}>{children}</WagmiConfig>;
}
